DROP VIEW IF EXISTS scv_map_segments;
DROP TABLE IF EXISTS planet_osm_line;
DROP TABLE IF EXISTS planet_osm_line_bb2; 
DROP TABLE IF EXISTS planet_osm_line_bb3;
DROP TABLE IF EXISTS planet_osm_line_bb_id;
DROP TABLE IF EXISTS planet_osm_line_ram;
DROP TABLE IF EXISTS planet_osm_point;
DROP TABLE IF EXISTS planet_osm_point_box2;
DROP TABLE IF EXISTS planet_osm_point_id;
DROP TABLE IF EXISTS planet_osm_point_line2;
DROP TABLE IF EXISTS planet_osm_point_line3;
DROP TABLE IF EXISTS planet_osm_polygon;
DROP TABLE IF EXISTS planet_osm_roads;
DROP TABLE IF EXISTS planet_osm_point_id0;
VACUUM;